#!/bin/sh

ENVTRACE_ROOT="$(readlink -f $(dirname "$0"))"

export LD_PRELOAD=${ENVTRACE_ROOT}/envtrace-helper.so:/lib64/libdl.so.2:${LD_PRELOAD}
export ENVTRACE_LOGFILE=${ENVTRACE_ROOT}/env.trace

echo "Writing ENVTRACE to: ${ENVTRACE_LOGFILE}"

exec "$@"

exit 1
